"""move_activity_type_id_from_segment_to_planned_session

Revision ID: 60932c425cfd
Revises: 77eca92898ff
Create Date: 2026-05-17 09:24:25.235276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60932c425cfd'
down_revision: Union[str, Sequence[str], None] = '77eca92898ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('planned_cardio_segments_activity_type_id_fkey'), 'planned_cardio_segments', type_='foreignkey')
    op.drop_column('planned_cardio_segments', 'activity_type_id')
    op.add_column('planned_sessions', sa.Column('activity_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'planned_sessions', 'cardio_activity_types', ['activity_type_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'planned_sessions', type_='foreignkey')
    op.drop_column('planned_sessions', 'activity_type_id')
    op.add_column('planned_cardio_segments', sa.Column('activity_type_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('planned_cardio_segments_activity_type_id_fkey'), 'planned_cardio_segments', 'cardio_activity_types', ['activity_type_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###
