"""add_template_id_to_strength_sessions

Revision ID: 77eca92898ff
Revises: 186afe24426c
Create Date: 2026-05-16 22:09:04.823301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77eca92898ff'
down_revision: Union[str, Sequence[str], None] = '186afe24426c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strength_sessions', sa.Column('template_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'strength_sessions', 'strength_templates', ['template_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'strength_sessions', type_='foreignkey')
    op.drop_column('strength_sessions', 'template_id')
    # ### end Alembic commands ###
