"""phase15_strava_imports_body_metrics

Revision ID: bdc9905e1b7f
Revises: 0014
Create Date: 2026-05-23 22:16:34.338319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bdc9905e1b7f'
down_revision: Union[str, Sequence[str], None] = '0014'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('body_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('resting_hr_bpm', sa.Float(), nullable=True),
    sa.Column('hrv_sdnn_ms', sa.Float(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('sleep_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('sleep_quality', sa.Integer(), nullable=True),
    sa.Column('vo2_max', sa.Float(), nullable=True),
    sa.Column('active_energy_kcal', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    op.create_table('pending_imports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('external_id', sa.Text(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('mapped_session', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', name='uq_pending_import_source_external_id')
    )
    op.add_column('user_settings', sa.Column('strava_access_token', sa.Text(), nullable=True))
    op.add_column('user_settings', sa.Column('strava_refresh_token', sa.Text(), nullable=True))
    op.add_column('user_settings', sa.Column('strava_token_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user_settings', sa.Column('strava_athlete_id', sa.BigInteger(), nullable=True))
    op.add_column('user_settings', sa.Column('strava_last_synced_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user_settings', sa.Column('strava_sync_start_date', sa.Date(), nullable=True))
    op.add_column('user_settings', sa.Column('health_metric_resting_hr', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('user_settings', sa.Column('health_metric_hrv', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('user_settings', sa.Column('health_metric_weight', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('user_settings', sa.Column('health_metric_sleep', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('user_settings', sa.Column('health_metric_vo2_max', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('user_settings', sa.Column('health_metric_active_energy', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'health_metric_active_energy')
    op.drop_column('user_settings', 'health_metric_vo2_max')
    op.drop_column('user_settings', 'health_metric_sleep')
    op.drop_column('user_settings', 'health_metric_weight')
    op.drop_column('user_settings', 'health_metric_hrv')
    op.drop_column('user_settings', 'health_metric_resting_hr')
    op.drop_column('user_settings', 'strava_sync_start_date')
    op.drop_column('user_settings', 'strava_last_synced_at')
    op.drop_column('user_settings', 'strava_athlete_id')
    op.drop_column('user_settings', 'strava_token_expires_at')
    op.drop_column('user_settings', 'strava_refresh_token')
    op.drop_column('user_settings', 'strava_access_token')
    op.drop_table('pending_imports')
    op.drop_table('body_metrics')
    # ### end Alembic commands ###
